id: A1A119146
title: 'The Heart of the Mahāyāna Path: A Bodhisattva’s Prayer of Aspiration'
type: translation
pechas:
- I8EFBEB6F
- I10BF4D70
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:56:17.354278
  last_modified_at: 2023-01-04 11:56:17.354283
  collections:
  - Gatön Ngawang Lekpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I8EFBEB6F/B42B: EB33
  I10BF4D70/29EA: EB33
